name: Deploy to Google Cloud

on:
  push:
    branches: [ cloud-infrastructure ]
  pull_request:
    branches: [ cloud-infrastructure ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: us-central1
  REPOSITORY: iot-pipeline
  
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install flake8 pytest black
        pip install -r src/requirements.txt
        pip install -r cloud/functions/requirements.txt
    
    - name: Lint with flake8
      run: |
        flake8 src/ cloud/functions/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 src/ cloud/functions/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Format check with black
      run: black --check src/ cloud/functions/
  
  deploy-infrastructure:
    if: github.ref == 'refs/heads/cloud-infrastructure'
    needs: lint-and-test
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write
    
    steps:
    - uses: actions/checkout@v4
    
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
    
    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0
    
    - name: 'Deploy with our deployment script'
      run: |
        # Create terraform.tfvars
        cd terraform
        cat > terraform.tfvars << EOF
        project_id = "$PROJECT_ID"
        region = "us-central1"
        EOF
        cd ..
        
        # Run deployment
        export GCP_PROJECT_ID="$PROJECT_ID"
        ./scripts/run-cloud.sh
    
    - name: 'Display Deployment Info'
      run: |
        cd terraform
        echo "Deployment Complete!"
        echo ""
        echo "Dashboard URL: $(terraform output -raw dashboard_url)"
        echo "Function Name: $(terraform output -raw function_name)"
        echo "BigQuery Dataset: $(terraform output -raw bigquery_dataset)"
        echo ""
        echo "Next steps from terraform output:"
        terraform output -raw next_steps
